In [8]:
import json
import os
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import random

### coco: 894 // flickr: 184 // open_image: 616

In [9]:
dir_path = "../Data/disaster/train"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)


disaster = img_names
print(len(disaster))

10057


In [10]:
## open_image 8000장
dir_path = "../../disk/Data/open_image/train_0/"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)
open_image_non = img_names[:15000]
print(len(open_image_non))

15000


In [11]:
## coco_image 1만장
dir_path = "../Data/train2017"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)
coco_non = img_names[:15000]
print(len(coco_non))

15000


In [12]:
print(coco_non[:3])

['../Data/train2017/000000095517.jpg', '../Data/train2017/000000082216.jpg', '../Data/train2017/000000117677.jpg']


In [13]:
non = coco_non + open_image_non
random.shuffle(non)
print(len(non))

30000


##### labeling

##### split train, test

In [7]:
### train: test (4:1)
## 36000 (1/4), 4000 (1/4)
# non_ratio=6400
# dis_ratio=6400
# trn_disater = non[:non_ratio] + disaster[:dis_ratio]
# tst_disater = non[non_ratio:] + disaster[dis_ratio:]
# trn_label = [0]*int(len(non[:non_ratio])) + [1]*int(len(disaster[:dis_ratio]))
# tst_label = [0]*int(len(non[non_ratio:])) + [1]*int(len(disaster[dis_ratio:]))
# print(len(trn_label))
# print(len(tst_label))

12800
3200


In [14]:
trn_disater = non + disaster
trn_label = [0]*int(len(non)) + [1]*int(len(disaster))
print(len(trn_label))

40057


In [15]:
trn_df = pd.DataFrame(trn_disater, columns=['image_id'])
trn_df['dir'] = trn_df['image_id'].apply(lambda x: os.path.dirname(x))
trn_df['image_id'] = trn_df['image_id'].apply(lambda x: os.path.basename(x))
trn_df['label'] = trn_label
train = trn_df
train

image_id  \
0                                       000000273230.jpg   
1                                       000000562664.jpg   
2                                   046cbbb3909854b9.jpg   
3                                   048a2aefcf5a073b.jpg   
4                                   07e726531536e603.jpg   
...                                                  ...   
40052                  earthquake_072_HorizontalFlip.jpg   
40053  A stop sign in the middle of a flooded street....   
40054                thunderstorm_121_HorizontalFlip.jpg   
40055                             fog_161_CenterCrop.jpg   
40056                    thunderstorm_247_CenterCrop.jpg   

                                                   dir  label  
0                                    ../Data/train2017      0  
1                                    ../Data/train2017      0  
2                   ../../disk/Data/open_image/train_0      0  
3                   ../../disk/Data/open_image/train_0      0  
4                   ../../disk/Data/open_image/train_0      0  
...                                                ...    ...  
40052  ../Data/disaster/train/augmented/HorizontalFlip      1  
40053           ../Data/disaster/train/generated1/coco      1  
40054  ../Data/disaster/train/augmented/HorizontalFlip      1  
40055      ../Data/disaster/train/augmented/CenterCrop      1  
40056      ../Data/disaster/train/augmented/CenterCrop      1  

[40057 rows x 3 columns]

In [16]:
project_name = 'disaster_classfication_inception_resnet_v2_3010_a'
user = 'hojunking'
run_name = 'disaster_classfication_inception_resnet_v2_3010_a'

In [17]:
%run classification_baseline.ipynb

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: hojunking. Use `wandb login --relogin` to force relogin


Training start with fold: 0 epoch: 200 

All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training p

epoch 0 loss: 0.0795: 100%|███████████████████| 126/126 [02:00<00:00,  1.04it/s]


Fold: 0
Epoch 1/199


epoch 1 loss: 0.0650: 100%|███████████████████| 126/126 [00:17<00:00,  7.10it/s]


Fold: 0
Epoch 2/199


epoch 2 loss: 0.0631: 100%|███████████████████| 126/126 [00:17<00:00,  7.31it/s]


Fold: 0
Epoch 3/199


epoch 3 loss: 0.0636: 100%|███████████████████| 126/126 [00:17<00:00,  7.36it/s]


Fold: 0
Epoch 4/199


epoch 4 loss: 0.0640: 100%|███████████████████| 126/126 [00:17<00:00,  7.40it/s]


Fold: 0
Epoch 5/199


epoch 5 loss: 0.0643: 100%|███████████████████| 126/126 [00:17<00:00,  7.41it/s]


Fold: 0
Epoch 6/199


epoch 6 loss: 0.0645: 100%|███████████████████| 126/126 [00:17<00:00,  7.19it/s]


Fold: 0
Epoch 7/199


epoch 7 loss: 0.0649: 100%|███████████████████| 126/126 [00:17<00:00,  7.38it/s]


Fold: 0
Epoch 8/199


epoch 8 loss: 0.0653: 100%|███████████████████| 126/126 [00:17<00:00,  7.33it/s]


Fold: 0
Epoch 9/199


epoch 9 loss: 0.0656: 100%|███████████████████| 126/126 [00:16<00:00,  7.55it/s]


Fold: 0
Epoch 10/199


epoch 10 loss: 0.0661: 100%|██████████████████| 126/126 [00:17<00:00,  7.32it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9775374371375016
Fold: 0
Epoch 11/199



epoch 11 loss: 0.0666: 100%|██████████████████| 126/126 [00:16<00:00,  7.53it/s]


Fold: 0
Epoch 12/199


epoch 12 loss: 0.0672: 100%|██████████████████| 126/126 [00:16<00:00,  7.49it/s]


Fold: 0
Epoch 13/199


epoch 13 loss: 0.0676: 100%|██████████████████| 126/126 [00:17<00:00,  7.38it/s]


Fold: 0
Epoch 14/199


epoch 14 loss: 0.0681: 100%|██████████████████| 126/126 [00:17<00:00,  7.38it/s]


Fold: 0
Epoch 15/199


epoch 15 loss: 0.0682: 100%|██████████████████| 126/126 [00:17<00:00,  7.31it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9788825962931416
Fold: 0
Epoch 16/199



epoch 16 loss: 0.0686: 100%|██████████████████| 126/126 [00:17<00:00,  7.23it/s]


Fold: 0
Epoch 17/199


epoch 17 loss: 0.0688: 100%|██████████████████| 126/126 [00:16<00:00,  7.50it/s]


Fold: 0
Epoch 18/199


epoch 18 loss: 0.0690: 100%|██████████████████| 126/126 [00:17<00:00,  7.29it/s]


Fold: 0
Epoch 19/199


epoch 19 loss: 0.0689: 100%|██████████████████| 126/126 [00:17<00:00,  7.33it/s]


Fold: 0
Epoch 20/199


epoch 20 loss: 0.0691: 100%|██████████████████| 126/126 [00:16<00:00,  7.45it/s]


Fold: 0
Epoch 21/199


epoch 21 loss: 0.0694: 100%|██████████████████| 126/126 [00:16<00:00,  7.50it/s]


Fold: 0
Epoch 22/199


epoch 22 loss: 0.0698: 100%|██████████████████| 126/126 [00:16<00:00,  7.50it/s]


Fold: 0
Epoch 23/199


epoch 23 loss: 0.0703: 100%|██████████████████| 126/126 [00:17<00:00,  7.35it/s]


EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9800432330194988
Fold: 0
Epoch 24/199


epoch 24 loss: 0.0708: 100%|██████████████████| 126/126 [00:16<00:00,  7.41it/s]


Fold: 0
Epoch 25/199


epoch 25 loss: 0.0716: 100%|██████████████████| 126/126 [00:17<00:00,  7.31it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9802128264479042
Fold: 0
Epoch 26/199



epoch 26 loss: 0.0718: 100%|██████████████████| 126/126 [00:16<00:00,  7.49it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9802128264479042
Fold: 0
Epoch 27/199



epoch 27 loss: 0.0720: 100%|██████████████████| 126/126 [00:17<00:00,  7.34it/s]


EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9802128264479042
Fold: 0
Epoch 28/199


epoch 28 loss: 0.0722: 100%|██████████████████| 126/126 [00:17<00:00,  7.29it/s]


EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9802128264479042
Fold: 0
Epoch 29/199


epoch 29 loss: 0.0723: 100%|██████████████████| 126/126 [00:16<00:00,  7.42it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9802128264479042
stop called
time : 1:04:29
fold: 0, Best Epoch : 24/ 30
fold: 0, Best Train Marco F1 : 1.00000
[[24000     0]
 [    0  8045]]
fold: 0, Best Valid Marco F1 : 0.98021
[[5947   53]
 [  66 1946]]
---------------------------------------------------------
Training start with fold: 1 epoch: 200 

All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
Al

epoch 0 loss: 0.0768: 100%|███████████████████| 126/126 [00:16<00:00,  7.51it/s]


Fold: 1
Epoch 1/199


epoch 1 loss: 0.0596: 100%|███████████████████| 126/126 [00:17<00:00,  7.31it/s]


Fold: 1
Epoch 2/199


epoch 2 loss: 0.0584: 100%|███████████████████| 126/126 [00:17<00:00,  7.40it/s]


Fold: 1
Epoch 3/199


epoch 3 loss: 0.0591: 100%|███████████████████| 126/126 [00:16<00:00,  7.41it/s]


Fold: 1
Epoch 4/199


epoch 4 loss: 0.0595: 100%|███████████████████| 126/126 [00:17<00:00,  7.36it/s]


Fold: 1
Epoch 5/199


epoch 5 loss: 0.0602: 100%|███████████████████| 126/126 [00:17<00:00,  7.22it/s]


Fold: 1
Epoch 6/199


epoch 6 loss: 0.0604: 100%|███████████████████| 126/126 [00:17<00:00,  7.37it/s]


Fold: 1
Epoch 7/199


epoch 7 loss: 0.0607: 100%|███████████████████| 126/126 [00:17<00:00,  7.17it/s]


Fold: 1
Epoch 8/199


epoch 8 loss: 0.0613: 100%|███████████████████| 126/126 [00:16<00:00,  7.49it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9793780074534821
Fold: 1
Epoch 9/199



epoch 9 loss: 0.0620: 100%|███████████████████| 126/126 [00:17<00:00,  7.40it/s]


Fold: 1
Epoch 10/199


epoch 10 loss: 0.0623: 100%|██████████████████| 126/126 [00:17<00:00,  7.38it/s]


Fold: 1
Epoch 11/199


epoch 11 loss: 0.0629: 100%|██████████████████| 126/126 [00:16<00:00,  7.42it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9802128264479042
Fold: 1
Epoch 12/199



epoch 12 loss: 0.0634: 100%|██████████████████| 126/126 [00:16<00:00,  7.45it/s]


EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9802128264479042
Fold: 1
Epoch 13/199


epoch 13 loss: 0.0641: 100%|██████████████████| 126/126 [00:17<00:00,  7.27it/s]


Fold: 1
Epoch 14/199


epoch 14 loss: 0.0638: 100%|██████████████████| 126/126 [00:17<00:00,  7.35it/s]


Fold: 1
Epoch 15/199


epoch 15 loss: 0.0645: 100%|██████████████████| 126/126 [00:17<00:00,  7.17it/s]


Fold: 1
Epoch 16/199


epoch 16 loss: 0.0649: 100%|██████████████████| 126/126 [00:17<00:00,  7.38it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9810473673883444
Fold: 1
Epoch 17/199



epoch 17 loss: 0.0654: 100%|██████████████████| 126/126 [00:16<00:00,  7.49it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9810473673883444
Fold: 1
Epoch 18/199



epoch 18 loss: 0.0657: 100%|██████████████████| 126/126 [00:17<00:00,  7.30it/s]


Fold: 1
Epoch 19/199


epoch 19 loss: 0.0662: 100%|██████████████████| 126/126 [00:17<00:00,  7.27it/s]


Fold: 1
Epoch 20/199


epoch 20 loss: 0.0665: 100%|██████████████████| 126/126 [00:17<00:00,  7.25it/s]


Fold: 1
Epoch 21/199


epoch 21 loss: 0.0668: 100%|██████████████████| 126/126 [00:17<00:00,  7.40it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9817184400808661
Fold: 1
Epoch 22/199



epoch 22 loss: 0.0672: 100%|██████████████████| 126/126 [00:16<00:00,  7.53it/s]


EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9817184400808661
Fold: 1
Epoch 23/199


epoch 23 loss: 0.0675: 100%|██████████████████| 126/126 [00:17<00:00,  7.12it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9817184400808661
Fold: 1
Epoch 24/199



epoch 24 loss: 0.0678: 100%|██████████████████| 126/126 [00:17<00:00,  7.35it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9817184400808661
Fold: 1
Epoch 25/199



epoch 25 loss: 0.0680: 100%|██████████████████| 126/126 [00:16<00:00,  7.48it/s]


Fold: 1
Epoch 26/199


epoch 26 loss: 0.0682: 100%|██████████████████| 126/126 [00:17<00:00,  7.32it/s]


EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9820567828618902
Fold: 1
Epoch 27/199


epoch 27 loss: 0.0684: 100%|██████████████████| 126/126 [00:17<00:00,  7.34it/s]


Fold: 1
Epoch 28/199


epoch 28 loss: 0.0685: 100%|██████████████████| 126/126 [00:16<00:00,  7.43it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9822199767774833
Fold: 1
Epoch 29/199



epoch 29 loss: 0.0687: 100%|██████████████████| 126/126 [00:17<00:00,  7.34it/s]


Fold: 1
Epoch 30/199


epoch 30 loss: 0.0689: 100%|██████████████████| 126/126 [00:17<00:00,  7.23it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.982389064660744
Fold: 1
Epoch 31/199



epoch 31 loss: 0.0690: 100%|██████████████████| 126/126 [00:17<00:00,  7.21it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.982389064660744
Fold: 1
Epoch 32/199



epoch 32 loss: 0.0692: 100%|██████████████████| 126/126 [00:17<00:00,  7.33it/s]


EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.982389064660744
Fold: 1
Epoch 33/199


epoch 33 loss: 0.0694: 100%|██████████████████| 126/126 [00:16<00:00,  7.44it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.982389064660744
Fold: 1
Epoch 34/199



epoch 34 loss: 0.0696: 100%|██████████████████| 126/126 [00:17<00:00,  7.33it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.982389064660744
stop called
time : 1:05:05
fold: 1, Best Epoch : 29/ 35
fold: 1, Best Train Marco F1 : 1.00000
[[24000     0]
 [    0  8045]]
fold: 1, Best Valid Marco F1 : 0.98239
[[5951   49]
 [  57 1955]]
---------------------------------------------------------
Training start with fold: 2 epoch: 200 

All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All

epoch 0 loss: 0.0876: 100%|███████████████████| 126/126 [00:17<00:00,  7.27it/s]


Fold: 2
Epoch 1/199


epoch 1 loss: 0.0782: 100%|███████████████████| 126/126 [00:16<00:00,  7.49it/s]


Fold: 2
Epoch 2/199


epoch 2 loss: 0.0766: 100%|███████████████████| 126/126 [00:16<00:00,  7.45it/s]


Fold: 2
Epoch 3/199


epoch 3 loss: 0.0767: 100%|███████████████████| 126/126 [00:16<00:00,  7.59it/s]


Fold: 2
Epoch 4/199


epoch 4 loss: 0.0773: 100%|███████████████████| 126/126 [00:17<00:00,  7.39it/s]


Fold: 2
Epoch 5/199


epoch 5 loss: 0.0783: 100%|███████████████████| 126/126 [00:17<00:00,  7.38it/s]


Fold: 2
Epoch 6/199


epoch 6 loss: 0.0792: 100%|███████████████████| 126/126 [00:16<00:00,  7.43it/s]


Fold: 2
Epoch 7/199


epoch 7 loss: 0.0801: 100%|███████████████████| 126/126 [00:17<00:00,  7.23it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9745498334233698
Fold: 2
Epoch 8/199



epoch 8 loss: 0.0810: 100%|███████████████████| 126/126 [00:17<00:00,  7.35it/s]


Fold: 2
Epoch 9/199


epoch 9 loss: 0.0818: 100%|███████████████████| 126/126 [00:17<00:00,  7.38it/s]


EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.975053001860982
Fold: 2
Epoch 10/199


epoch 10 loss: 0.0826: 100%|██████████████████| 126/126 [00:16<00:00,  7.48it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.975053001860982
Fold: 2
Epoch 11/199



epoch 11 loss: 0.0833: 100%|██████████████████| 126/126 [00:17<00:00,  7.33it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.975053001860982
Fold: 2
Epoch 12/199



epoch 12 loss: 0.0840: 100%|██████████████████| 126/126 [00:16<00:00,  7.44it/s]


EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.975053001860982
Fold: 2
Epoch 13/199


epoch 13 loss: 0.0847: 100%|██████████████████| 126/126 [00:17<00:00,  7.36it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.975053001860982
stop called
time : 0:26:19
fold: 2, Best Epoch : 8/ 14
fold: 2, Best Train Marco F1 : 1.00000
[[24000     0]
 [    0  8046]]
fold: 2, Best Valid Marco F1 : 0.97505
[[5931   69]
 [  81 1930]]
---------------------------------------------------------
Training start with fold: 3 epoch: 200 

All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All 

epoch 0 loss: 0.0890: 100%|███████████████████| 126/126 [00:17<00:00,  7.38it/s]


Fold: 3
Epoch 1/199


epoch 1 loss: 0.0760: 100%|███████████████████| 126/126 [00:16<00:00,  7.47it/s]


Fold: 3
Epoch 2/199


epoch 2 loss: 0.0745: 100%|███████████████████| 126/126 [00:17<00:00,  7.41it/s]


Fold: 3
Epoch 3/199


epoch 3 loss: 0.0737: 100%|███████████████████| 126/126 [00:17<00:00,  7.41it/s]


Fold: 3
Epoch 4/199


epoch 4 loss: 0.0738: 100%|███████████████████| 126/126 [00:16<00:00,  7.44it/s]


Fold: 3
Epoch 5/199


epoch 5 loss: 0.0750: 100%|███████████████████| 126/126 [00:17<00:00,  7.39it/s]


Fold: 3
Epoch 6/199


epoch 6 loss: 0.0740: 100%|███████████████████| 126/126 [00:17<00:00,  7.33it/s]


Fold: 3
Epoch 7/199


epoch 7 loss: 0.0773: 100%|███████████████████| 126/126 [00:17<00:00,  7.27it/s]


EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9739945333658955
Fold: 3
Epoch 8/199


epoch 8 loss: 0.0783: 100%|███████████████████| 126/126 [00:16<00:00,  7.45it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9739945333658955
Fold: 3
Epoch 9/199



epoch 9 loss: 0.0790: 100%|███████████████████| 126/126 [00:16<00:00,  7.44it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9739945333658955
Fold: 3
Epoch 10/199



epoch 10 loss: 0.0797: 100%|██████████████████| 126/126 [00:16<00:00,  7.61it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9739945333658955
Fold: 3
Epoch 11/199



epoch 11 loss: 0.0806: 100%|██████████████████| 126/126 [00:16<00:00,  7.58it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9739945333658955
stop called
time : 0:22:32
fold: 3, Best Epoch : 6/ 12
fold: 3, Best Train Marco F1 : 1.00000
[[24000     0]
 [    0  8046]]
fold: 3, Best Valid Marco F1 : 0.97399
[[5935   65]
 [  91 1920]]
---------------------------------------------------------
Training start with fold: 4 epoch: 200 

All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All training process
All

epoch 0 loss: 0.0924: 100%|███████████████████| 126/126 [00:17<00:00,  7.25it/s]


Fold: 4
Epoch 1/199


epoch 1 loss: 0.0766: 100%|███████████████████| 126/126 [00:17<00:00,  7.24it/s]


Fold: 4
Epoch 2/199


epoch 2 loss: 0.0767: 100%|███████████████████| 126/126 [00:17<00:00,  7.32it/s]


Fold: 4
Epoch 3/199


epoch 3 loss: 0.0760: 100%|███████████████████| 126/126 [00:17<00:00,  7.24it/s]


Fold: 4
Epoch 4/199


epoch 4 loss: 0.0752: 100%|███████████████████| 126/126 [00:17<00:00,  7.38it/s]


Fold: 4
Epoch 5/199


epoch 5 loss: 0.0754: 100%|███████████████████| 126/126 [00:17<00:00,  7.24it/s]


Fold: 4
Epoch 6/199


epoch 6 loss: 0.0761: 100%|███████████████████| 126/126 [00:17<00:00,  7.26it/s]


Fold: 4
Epoch 7/199


epoch 7 loss: 0.0764: 100%|███████████████████| 126/126 [00:17<00:00,  7.22it/s]


Fold: 4
Epoch 8/199


epoch 8 loss: 0.0768: 100%|███████████████████| 126/126 [00:17<00:00,  7.16it/s]


Fold: 4
Epoch 9/199


epoch 9 loss: 0.0773: 100%|███████████████████| 126/126 [00:17<00:00,  7.35it/s]


Fold: 4
Epoch 10/199


epoch 10 loss: 0.0778: 100%|██████████████████| 126/126 [00:17<00:00,  7.34it/s]


Fold: 4
Epoch 11/199


epoch 11 loss: 0.0784: 100%|██████████████████| 126/126 [00:17<00:00,  7.06it/s]


Fold: 4
Epoch 12/199


epoch 12 loss: 0.0789: 100%|██████████████████| 126/126 [00:17<00:00,  7.41it/s]


Fold: 4
Epoch 13/199


epoch 13 loss: 0.0793: 100%|██████████████████| 126/126 [00:16<00:00,  7.49it/s]


Fold: 4
Epoch 14/199


epoch 14 loss: 0.0798: 100%|██████████████████| 126/126 [00:17<00:00,  7.10it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9730844051589703
Fold: 4
Epoch 15/199



epoch 15 loss: 0.0804: 100%|██████████████████| 126/126 [00:17<00:00,  7.26it/s]


Fold: 4
Epoch 16/199


epoch 16 loss: 0.0808: 100%|██████████████████| 126/126 [00:17<00:00,  7.31it/s]


Fold: 4
Epoch 17/199


epoch 17 loss: 0.0812: 100%|██████████████████| 126/126 [00:16<00:00,  7.43it/s]


Fold: 4
Epoch 18/199


epoch 18 loss: 0.0817: 100%|██████████████████| 126/126 [00:17<00:00,  7.20it/s]


Fold: 4
Epoch 19/199


epoch 19 loss: 0.0822: 100%|██████████████████| 126/126 [00:17<00:00,  7.17it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.974447607121872
Fold: 4
Epoch 20/199



epoch 20 loss: 0.0826: 100%|██████████████████| 126/126 [00:17<00:00,  7.26it/s]


Fold: 4
Epoch 21/199


epoch 21 loss: 0.0830: 100%|██████████████████| 126/126 [00:17<00:00,  7.34it/s]


EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9746103536925572
Fold: 4
Epoch 22/199


epoch 22 loss: 0.0835: 100%|██████████████████| 126/126 [00:17<00:00,  7.07it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9746103536925572
Fold: 4
Epoch 23/199



epoch 23 loss: 0.0839: 100%|██████████████████| 126/126 [00:17<00:00,  7.15it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9746103536925572
Fold: 4
Epoch 24/199



epoch 24 loss: 0.0843: 100%|██████████████████| 126/126 [00:17<00:00,  7.23it/s]


EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9746103536925572
Fold: 4
Epoch 25/199


epoch 25 loss: 0.0846: 100%|██████████████████| 126/126 [00:17<00:00,  7.11it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9746103536925572
stop called
time : 0:48:53
fold: 4, Best Epoch : 20/ 26
fold: 4, Best Train Marco F1 : 1.00000
[[24000     0]
 [    0  8046]]
fold: 4, Best Valid Marco F1 : 0.97461
[[5943   57]
 [  95 1916]]
---------------------------------------------------------
best_fold : 0.982389064660744
 Top fold : 1


In [18]:
dir_path = "../Data/disaster/test"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)

disaster_test = img_names
print(len(disaster_test))

400


In [19]:
## open_image 1만장
dir_path = "../../disk/Data/open_image/train_1/"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)
open_image_non_test = img_names[:20000]
print(len(open_image_non_test))

20000


In [20]:
tst_disater = open_image_non_test + disaster_test
tst_label = [0]*int(len(open_image_non_test)) + [1]*int(len(disaster_test))
print(len(tst_label))

20400


In [21]:
tst_df = pd.DataFrame(tst_disater, columns=['image_id'])
tst_df['dir'] = tst_df['image_id'].apply(lambda x: os.path.dirname(x))
tst_df['image_id'] = tst_df['image_id'].apply(lambda x: os.path.basename(x))
tst_df['label'] = tst_label
test = tst_df
test

image_id  \
0                   136458d0da88828b.jpg   
1                   10745c353b5ac23c.jpg   
2                   1acdf3a5be90b86a.jpg   
3                   1e96463d79b68919.jpg   
4                   116ea9f20bc62c1d.jpg   
...                                  ...   
20395  blizzard_disasterblizzard_123.jpg   
20396                    tempest_043.jpg   
20397               32ce6407b55b36a5.jpg   
20398                   000000328569.jpg   
20399               thunderstorm_346.jpg   

                                                     dir  label  
0                     ../../disk/Data/open_image/train_1      0  
1                     ../../disk/Data/open_image/train_1      0  
2                     ../../disk/Data/open_image/train_1      0  
3                     ../../disk/Data/open_image/train_1      0  
4                     ../../disk/Data/open_image/train_1      0  
...                                                  ...    ...  
20395  ../Data/disaster/test/origin_images/crawling/b...      1  
20396  ../Data/disaster/test/origin_images/crawling/t...      1  
20397  ../Data/disaster/test/origin_images/open_image...      1  
20398  ../Data/disaster/test/origin_images/COCO_disaster      1  
20399  ../Data/disaster/test/origin_images/crawling/t...      1  

[20400 rows x 3 columns]

In [24]:
dist.destroy_process_group()

In [22]:
model_name = 'tf_efficientnet_b2_ns'
model_dir = model_name + '/tf_efficientnet_b2_ns_1'
%run eval_test.ipynb

100%|█████████████████████████████████████████| 160/160 [06:00<00:00,  2.25s/it]


In [23]:
print(f'accuracy: {test_acc:.4f}')
print(f'f1_score: {epoch_f1:.4f}')
print(f'confusion_matrix \n-------------------------\n {test_matrix}')

accuracy: 0.9800
f1_score: 0.8080
confusion_matrix 
-------------------------
 [[19652   348]
 [   59   341]]


In [11]:
non_matched_idx = test['label'] != test['pred']
non_matched = test[non_matched_idx].reset_index(inplace = False, drop=True)
non_matched

image_id  \
0                 13d191db596a5e4a.jpg   
1                 1cfd32a632fa0771.jpg   
2                 1a7a43cb6ae3ed7b.jpg   
3                 1410f35aeb2ae8af.jpg   
4                 13628048cf4a80cd.jpg   
..                                 ...   
558  blizzard_disasterblizzard_305.jpg   
559                    tempest_041.jpg   
560                   000000073187.jpg   
561                   000000234697.jpg   
562                   000000213826.jpg   

                                                   dir  label  pred  \
0                   ../../disk/Data/open_image/train_1      0     1   
1                   ../../disk/Data/open_image/train_1      0     1   
2                   ../../disk/Data/open_image/train_1      0     1   
3                   ../../disk/Data/open_image/train_1      0     1   
4                   ../../disk/Data/open_image/train_1      0     1   
..                                                 ...    ...   ...   
558  ../Data/disaster/test/origin_images/crawling/b...      1     0   
559  ../Data/disaster/test/origin_images/crawling/t...      1     0   
560  ../Data/disaster/test/origin_images/COCO_disaster      1     0   
561  ../Data/disaster/test/origin_images/COCO_disaster      1     0   
562  ../Data/disaster/test/origin_images/COCO_disaster      1     0   

     confidence score  
0            0.918041  
1            0.700170  
2            0.665575  
3            0.993265  
4            0.930421  
..                ...  
558          0.924526  
559          0.999252  
560          0.999304  
561          0.999646  
562          0.992844  

[563 rows x 5 columns]

In [ ]:
## show img status

back = 0
plt.figure(figsize=(16,600))
for i in range(len(non_matched[back:])):
    plt.subplot(150,4,i+1)
    #if i % 4 == 0:
        #plt.title(f"{(i+1+back)/4}")
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    path = non_matched['dir'][i+back] + '/' + non_matched['image_id'][i+back]
    im_bgr = cv2.imread(path)
    im_rgb = im_bgr[:, :, ::-1]
    plt.imshow(im_rgb, cmap=plt.cm.binary)
    
plt.show()

In [24]:
test.to_csv('test_result/nsb2_oi_tst.csv', index=False)

In [8]:
test_acc = np.sum(test.label == test.pred) / len(test)
test_acc

0.9963420273292325

NameError: name 'model' is not defined