In [1]:
import json
import os
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import random

### coco: 894 // flickr: 184 // open_image: 616

In [2]:
dir_path = "../Data/disaster/train"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)


disaster = img_names
print(len(disaster))

10057


In [3]:
## open_image 8000장
dir_path = "../../disk/Data/open_image/train_0/"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)
open_image_non = img_names[:25000]
print(len(open_image_non))

25000


In [4]:
## coco_image 1만장
dir_path = "../Data/train2017"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)
coco_non = img_names[:25000]
print(len(coco_non))

25000


In [5]:
print(coco_non[:3])

['../Data/train2017/000000536626.jpg', '../Data/train2017/000000067396.jpg', '../Data/train2017/000000404997.jpg']


In [6]:
non = coco_non + open_image_non
random.shuffle(non)
print(len(non))

50000


##### labeling

##### split train, test

In [7]:
### train: test (4:1)
## 36000 (1/4), 4000 (1/4)
# non_ratio=6400
# dis_ratio=6400
# trn_disater = non[:non_ratio] + disaster[:dis_ratio]
# tst_disater = non[non_ratio:] + disaster[dis_ratio:]
# trn_label = [0]*int(len(non[:non_ratio])) + [1]*int(len(disaster[:dis_ratio]))
# tst_label = [0]*int(len(non[non_ratio:])) + [1]*int(len(disaster[dis_ratio:]))
# print(len(trn_label))
# print(len(tst_label))

12800
3200


In [7]:
trn_disater = non + disaster
trn_label = [0]*int(len(non)) + [1]*int(len(disaster))
print(len(trn_label))

60057


In [8]:
trn_df = pd.DataFrame(trn_disater, columns=['image_id'])
trn_df['dir'] = trn_df['image_id'].apply(lambda x: os.path.dirname(x))
trn_df['image_id'] = trn_df['image_id'].apply(lambda x: os.path.basename(x))
trn_df['label'] = trn_label
train = trn_df
train

image_id  \
0                   000000260238.jpg   
1                   000000127585.jpg   
2               020fb523136ee375.jpg   
3               0535012b246089ba.jpg   
4                   000000305351.jpg   
...                              ...   
60052      blizzard_025_contrast.jpg   
60053                  211981411.jpg   
60054       tempest_145_contrast.jpg   
60055  earthquake_282_rotatation.jpg   
60056     tempest_080_rotatation.jpg   

                                                     dir  label  
0                                      ../Data/train2017      0  
1                                      ../Data/train2017      0  
2                     ../../disk/Data/open_image/train_0      0  
3                     ../../disk/Data/open_image/train_0      0  
4                                      ../Data/train2017      0  
...                                                  ...    ...  
60052          ../Data/disaster/train/augmented/contrast      1  
60053  ../Data/disaster/train/origin_images/flickr30k...      1  
60054          ../Data/disaster/train/augmented/contrast      1  
60055        ../Data/disaster/train/augmented/rotatation      1  
60056        ../Data/disaster/train/augmented/rotatation      1  

[60057 rows x 3 columns]

In [9]:
project_name = 'disaster_classfication_inception_resnet_v2_5010_a'
user = 'hojunking'
run_name = 'disaster_classfication_inception_resnet_v2_5010_a'

In [10]:
%run classification_baseline.ipynb

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: hojunking. Use `wandb login --relogin` to force relogin


Model: inception_resnet_v2
Training start with fold: 0 epoch: 200 

All training process
Fold: 0
Epoch 0/199


epoch 0 loss: 0.0403: 100%|███████████████████| 188/188 [02:37<00:00,  1.19it/s]


Fold: 0
Epoch 1/199


epoch 1 loss: 0.0443: 100%|███████████████████| 188/188 [00:59<00:00,  3.17it/s]


Fold: 0
Epoch 2/199


epoch 2 loss: 0.0385: 100%|███████████████████| 188/188 [00:58<00:00,  3.21it/s]


Fold: 0
Epoch 3/199


epoch 3 loss: 0.0427: 100%|███████████████████| 188/188 [00:58<00:00,  3.21it/s]


Fold: 0
Epoch 4/199


epoch 4 loss: 0.0483: 100%|███████████████████| 188/188 [00:58<00:00,  3.22it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9782863458854683
Fold: 0
Epoch 5/199



epoch 5 loss: 0.0436: 100%|███████████████████| 188/188 [00:58<00:00,  3.22it/s]


Fold: 0
Epoch 6/199


epoch 6 loss: 0.0477: 100%|███████████████████| 188/188 [00:58<00:00,  3.23it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9788863355595872
Fold: 0
Epoch 7/199



epoch 7 loss: 0.0446: 100%|███████████████████| 188/188 [00:58<00:00,  3.21it/s]


Fold: 0
Epoch 8/199


epoch 8 loss: 0.0447: 100%|███████████████████| 188/188 [00:58<00:00,  3.19it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9794528758483081
Fold: 0
Epoch 9/199



epoch 9 loss: 0.0424: 100%|███████████████████| 188/188 [00:58<00:00,  3.21it/s]


Fold: 0
Epoch 10/199


epoch 10 loss: 0.0450: 100%|██████████████████| 188/188 [00:58<00:00,  3.21it/s]


Fold: 0
Epoch 11/199


epoch 11 loss: 0.0388: 100%|██████████████████| 188/188 [00:58<00:00,  3.21it/s]


Fold: 0
Epoch 12/199


epoch 12 loss: 0.0530: 100%|██████████████████| 188/188 [00:58<00:00,  3.23it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9844713688750468
Fold: 0
Epoch 13/199



epoch 13 loss: 0.0505: 100%|██████████████████| 188/188 [00:58<00:00,  3.22it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9844713688750468
Fold: 0
Epoch 14/199



epoch 14 loss: 0.0413: 100%|██████████████████| 188/188 [00:58<00:00,  3.21it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9844713688750468
Fold: 0
Epoch 15/199



epoch 15 loss: 0.0515: 100%|██████████████████| 188/188 [00:59<00:00,  3.18it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9844713688750468
Fold: 0
Epoch 16/199



epoch 16 loss: 0.0382: 100%|██████████████████| 188/188 [00:58<00:00,  3.22it/s]


Fold: 0
Epoch 17/199


epoch 17 loss: 0.0456: 100%|██████████████████| 188/188 [00:59<00:00,  3.18it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9847030563324011
Fold: 0
Epoch 18/199



epoch 18 loss: 0.0417: 100%|██████████████████| 188/188 [00:58<00:00,  3.20it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9847030563324011
Fold: 0
Epoch 19/199



epoch 19 loss: 0.0515: 100%|██████████████████| 188/188 [00:58<00:00,  3.21it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9847030563324011
Fold: 0
Epoch 20/199



epoch 20 loss: 0.0381: 100%|██████████████████| 188/188 [00:58<00:00,  3.21it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9847030563324011
Fold: 0
Epoch 21/199



epoch 21 loss: 0.0374: 100%|██████████████████| 188/188 [00:58<00:00,  3.23it/s]


Fold: 0
Epoch 22/199


epoch 22 loss: 0.0388: 100%|██████████████████| 188/188 [00:58<00:00,  3.23it/s]


Fold: 0
Epoch 23/199


epoch 23 loss: 0.0392: 100%|██████████████████| 188/188 [00:58<00:00,  3.21it/s]


Fold: 0
Epoch 24/199


epoch 24 loss: 0.0397: 100%|██████████████████| 188/188 [00:59<00:00,  3.18it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9862357759820677
Fold: 0
Epoch 25/199



epoch 25 loss: 0.0400: 100%|██████████████████| 188/188 [00:58<00:00,  3.23it/s]


Fold: 0
Epoch 26/199


epoch 26 loss: 0.0402: 100%|██████████████████| 188/188 [00:58<00:00,  3.24it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9863826732519151
Fold: 0
Epoch 27/199



epoch 27 loss: 0.0405: 100%|██████████████████| 188/188 [00:58<00:00,  3.23it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9863826732519151
Fold: 0
Epoch 28/199



epoch 28 loss: 0.0408: 100%|██████████████████| 188/188 [00:58<00:00,  3.23it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9863826732519151
Fold: 0
Epoch 29/199



epoch 29 loss: 0.0411: 100%|██████████████████| 188/188 [00:58<00:00,  3.21it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9863826732519151
Fold: 0
Epoch 30/199



epoch 30 loss: 0.0413: 100%|██████████████████| 188/188 [00:58<00:00,  3.22it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9863826732519151
stop called
time : 3:04:12
fold: 0, Best Epoch : 25/ 31
fold: 0, Best Train Marco F1 : 1.00000
[[40000     0]
 [    0  8045]]
fold: 0, Best Valid Marco F1 : 0.98638
[[9961   39]
 [  52 1960]]
---------------------------------------------------------
Training start with fold: 1 epoch: 200 

All training process
Fold: 1
Epoch 0/199


epoch 0 loss: 0.0407: 100%|███████████████████| 188/188 [00:58<00:00,  3.20it/s]


Fold: 1
Epoch 1/199


epoch 1 loss: 0.0340: 100%|███████████████████| 188/188 [00:59<00:00,  3.17it/s]


Fold: 1
Epoch 2/199


epoch 2 loss: 0.0448: 100%|███████████████████| 188/188 [00:58<00:00,  3.21it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9795399503802358
Fold: 1
Epoch 3/199



epoch 3 loss: 0.0470: 100%|███████████████████| 188/188 [00:58<00:00,  3.19it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9795399503802358
Fold: 1
Epoch 4/199



epoch 4 loss: 0.0632: 100%|███████████████████| 188/188 [00:58<00:00,  3.21it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9795399503802358
Fold: 1
Epoch 5/199



epoch 5 loss: 0.0511: 100%|███████████████████| 188/188 [00:58<00:00,  3.22it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9795399503802358
Fold: 1
Epoch 6/199



epoch 6 loss: 0.0481: 100%|███████████████████| 188/188 [00:58<00:00,  3.21it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9795399503802358
stop called
time : 0:40:08
fold: 1, Best Epoch : 1/ 7
fold: 1, Best Train Marco F1 : 0.99298
[[39911    89]
 [   99  7946]]
fold: 1, Best Valid Marco F1 : 0.97954
[[9933   67]
 [  70 1942]]
---------------------------------------------------------
Training start with fold: 2 epoch: 200 

All training process
Fold: 2
Epoch 0/199


epoch 0 loss: 0.0448: 100%|███████████████████| 188/188 [01:01<00:00,  3.06it/s]


Fold: 2
Epoch 1/199


epoch 1 loss: 0.0488: 100%|███████████████████| 188/188 [01:01<00:00,  3.07it/s]


Fold: 2
Epoch 2/199


epoch 2 loss: 0.0614: 100%|███████████████████| 188/188 [01:00<00:00,  3.11it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9762560388356738
Fold: 2
Epoch 3/199



epoch 3 loss: 0.0653: 100%|███████████████████| 188/188 [01:00<00:00,  3.09it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9762560388356738
Fold: 2
Epoch 4/199



epoch 4 loss: 0.0560: 100%|███████████████████| 188/188 [01:00<00:00,  3.10it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9762560388356738
Fold: 2
Epoch 5/199



epoch 5 loss: 0.0510: 100%|███████████████████| 188/188 [01:00<00:00,  3.09it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9762560388356738
Fold: 2
Epoch 6/199



epoch 6 loss: 0.0645: 100%|███████████████████| 188/188 [01:00<00:00,  3.10it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9762560388356738
stop called
time : 0:40:49
fold: 2, Best Epoch : 1/ 7
fold: 2, Best Train Marco F1 : 0.99492
[[39934    66]
 [   70  7976]]
fold: 2, Best Valid Marco F1 : 0.97626
[[9888  112]
 [  49 1962]]
---------------------------------------------------------
Training start with fold: 3 epoch: 200 

All training process
Fold: 3
Epoch 0/199


epoch 0 loss: 0.0443: 100%|███████████████████| 188/188 [01:00<00:00,  3.10it/s]


Fold: 3
Epoch 1/199


epoch 1 loss: 0.0489: 100%|███████████████████| 188/188 [01:01<00:00,  3.06it/s]


Fold: 3
Epoch 2/199


epoch 2 loss: 0.0488: 100%|███████████████████| 188/188 [01:00<00:00,  3.09it/s]


Fold: 3
Epoch 3/199


epoch 3 loss: 0.0492: 100%|███████████████████| 188/188 [01:00<00:00,  3.09it/s]


Fold: 3
Epoch 4/199


epoch 4 loss: 0.0449: 100%|███████████████████| 188/188 [01:01<00:00,  3.08it/s]


Fold: 3
Epoch 5/199


epoch 5 loss: 0.0573: 100%|███████████████████| 188/188 [01:00<00:00,  3.09it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9792705981108498
Fold: 3
Epoch 6/199



epoch 6 loss: 0.0457: 100%|███████████████████| 188/188 [01:01<00:00,  3.08it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9792705981108498
Fold: 3
Epoch 7/199



epoch 7 loss: 0.0637: 100%|███████████████████| 188/188 [01:00<00:00,  3.10it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9792705981108498
Fold: 3
Epoch 8/199



epoch 8 loss: 0.0659: 100%|███████████████████| 188/188 [01:01<00:00,  3.05it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9792705981108498
Fold: 3
Epoch 9/199



epoch 9 loss: 0.0732: 100%|███████████████████| 188/188 [01:00<00:00,  3.10it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9792705981108498
stop called
time : 0:58:30
fold: 3, Best Epoch : 4/ 10
fold: 3, Best Train Marco F1 : 0.99761
[[39965    35]
 [   29  8017]]
fold: 3, Best Valid Marco F1 : 0.97927
[[9946   54]
 [  84 1927]]
---------------------------------------------------------
Training start with fold: 4 epoch: 200 

All training process
Fold: 4
Epoch 0/199


epoch 0 loss: 0.0482: 100%|███████████████████| 188/188 [01:00<00:00,  3.09it/s]


Fold: 4
Epoch 1/199


epoch 1 loss: 0.0487: 100%|███████████████████| 188/188 [01:01<00:00,  3.05it/s]


Fold: 4
Epoch 2/199


epoch 2 loss: 0.0600: 100%|███████████████████| 188/188 [01:01<00:00,  3.08it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9760479046338832
Fold: 4
Epoch 3/199



epoch 3 loss: 0.0584: 100%|███████████████████| 188/188 [01:00<00:00,  3.08it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9760479046338832
Fold: 4
Epoch 4/199



epoch 4 loss: 0.0574: 100%|███████████████████| 188/188 [01:01<00:00,  3.08it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9760479046338832
Fold: 4
Epoch 5/199



epoch 5 loss: 0.0524: 100%|███████████████████| 188/188 [01:00<00:00,  3.08it/s]


Fold: 4
Epoch 6/199


epoch 6 loss: 0.0536: 100%|███████████████████| 188/188 [01:00<00:00,  3.09it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9761283602969972
Fold: 4
Epoch 7/199



epoch 7 loss: 0.0475: 100%|███████████████████| 188/188 [01:00<00:00,  3.09it/s]


Fold: 4
Epoch 8/199


epoch 8 loss: 0.0425: 100%|███████████████████| 188/188 [01:01<00:00,  3.05it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9804758447300548
Fold: 4
Epoch 9/199



epoch 9 loss: 0.0440: 100%|███████████████████| 188/188 [01:00<00:00,  3.08it/s]


Fold: 4
Epoch 10/199


epoch 10 loss: 0.0505: 100%|██████████████████| 188/188 [01:00<00:00,  3.10it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9805063299356884
Fold: 4
Epoch 11/199



epoch 11 loss: 0.0579: 100%|██████████████████| 188/188 [01:00<00:00,  3.09it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9805063299356884
Fold: 4
Epoch 12/199



epoch 12 loss: 0.0618: 100%|██████████████████| 188/188 [01:00<00:00,  3.08it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9805063299356884
Fold: 4
Epoch 13/199



epoch 13 loss: 0.0502: 100%|██████████████████| 188/188 [01:00<00:00,  3.08it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9805063299356884
Fold: 4
Epoch 14/199



epoch 14 loss: 0.0532: 100%|██████████████████| 188/188 [01:00<00:00,  3.09it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9805063299356884
stop called
time : 1:27:48
fold: 4, Best Epoch : 9/ 15
fold: 4, Best Train Marco F1 : 0.99802
[[39977    23]
 [   30  8016]]
fold: 4, Best Valid Marco F1 : 0.98051
[[9906   94]
 [  38 1973]]
---------------------------------------------------------
best_fold : 0.9863826732519151
 Top fold : 0


In [11]:
dir_path = "../Data/disaster/test"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)

disaster_test = img_names
print(len(disaster_test))

400


In [12]:
## open_image 1만장
dir_path = "../../disk/Data/open_image/train_1/"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)
open_image_non_test = img_names[:20000]
print(len(open_image_non_test))

20000


In [13]:
tst_disater = open_image_non_test + disaster_test
tst_label = [0]*int(len(open_image_non_test)) + [1]*int(len(disaster_test))
print(len(tst_label))

20400


In [14]:
tst_df = pd.DataFrame(tst_disater, columns=['image_id'])
tst_df['dir'] = tst_df['image_id'].apply(lambda x: os.path.dirname(x))
tst_df['image_id'] = tst_df['image_id'].apply(lambda x: os.path.basename(x))
tst_df['label'] = tst_label
test = tst_df
test

image_id  \
0                   136458d0da88828b.jpg   
1                   10745c353b5ac23c.jpg   
2                   1acdf3a5be90b86a.jpg   
3                   1e96463d79b68919.jpg   
4                   116ea9f20bc62c1d.jpg   
...                                  ...   
20395  blizzard_disasterblizzard_123.jpg   
20396                    tempest_043.jpg   
20397               32ce6407b55b36a5.jpg   
20398                   000000328569.jpg   
20399               thunderstorm_346.jpg   

                                                     dir  label  
0                     ../../disk/Data/open_image/train_1      0  
1                     ../../disk/Data/open_image/train_1      0  
2                     ../../disk/Data/open_image/train_1      0  
3                     ../../disk/Data/open_image/train_1      0  
4                     ../../disk/Data/open_image/train_1      0  
...                                                  ...    ...  
20395  ../Data/disaster/test/origin_images/crawling/b...      1  
20396  ../Data/disaster/test/origin_images/crawling/t...      1  
20397  ../Data/disaster/test/origin_images/open_image...      1  
20398  ../Data/disaster/test/origin_images/COCO_disaster      1  
20399  ../Data/disaster/test/origin_images/crawling/t...      1  

[20400 rows x 3 columns]

In [12]:
dist.destroy_process_group()

In [15]:
model_name = 'inception_resnet_v2'
model_dir = model_name + '/inception_resnet_v2_0'
%run eval_test.ipynb

100%|█████████████████████████████████████████| 160/160 [06:14<00:00,  2.34s/it]


In [16]:
print(f'accuracy: {test_acc:.4f}')
print(f'f1_score: {epoch_f1:.4f}')
print(f'confusion_matrix \n-------------------------\n {test_matrix}')

accuracy: 0.9884
f1_score: 0.8648
confusion_matrix 
-------------------------
 [[19836   164]
 [   72   328]]


In [11]:
non_matched_idx = test['label'] != test['pred']
non_matched = test[non_matched_idx].reset_index(inplace = False, drop=True)
non_matched

image_id  \
0                 13d191db596a5e4a.jpg   
1                 1cfd32a632fa0771.jpg   
2                 1a7a43cb6ae3ed7b.jpg   
3                 1410f35aeb2ae8af.jpg   
4                 13628048cf4a80cd.jpg   
..                                 ...   
558  blizzard_disasterblizzard_305.jpg   
559                    tempest_041.jpg   
560                   000000073187.jpg   
561                   000000234697.jpg   
562                   000000213826.jpg   

                                                   dir  label  pred  \
0                   ../../disk/Data/open_image/train_1      0     1   
1                   ../../disk/Data/open_image/train_1      0     1   
2                   ../../disk/Data/open_image/train_1      0     1   
3                   ../../disk/Data/open_image/train_1      0     1   
4                   ../../disk/Data/open_image/train_1      0     1   
..                                                 ...    ...   ...   
558  ../Data/disaster/test/origin_images/crawling/b...      1     0   
559  ../Data/disaster/test/origin_images/crawling/t...      1     0   
560  ../Data/disaster/test/origin_images/COCO_disaster      1     0   
561  ../Data/disaster/test/origin_images/COCO_disaster      1     0   
562  ../Data/disaster/test/origin_images/COCO_disaster      1     0   

     confidence score  
0            0.918041  
1            0.700170  
2            0.665575  
3            0.993265  
4            0.930421  
..                ...  
558          0.924526  
559          0.999252  
560          0.999304  
561          0.999646  
562          0.992844  

[563 rows x 5 columns]

In [ ]:
## show img status

back = 0
plt.figure(figsize=(16,600))
for i in range(len(non_matched[back:])):
    plt.subplot(150,4,i+1)
    #if i % 4 == 0:
        #plt.title(f"{(i+1+back)/4}")
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    path = non_matched['dir'][i+back] + '/' + non_matched['image_id'][i+back]
    im_bgr = cv2.imread(path)
    im_rgb = im_bgr[:, :, ::-1]
    plt.imshow(im_rgb, cmap=plt.cm.binary)
    
plt.show()

In [24]:
test.to_csv('test_result/nsb2_oi_tst.csv', index=False)

In [8]:
test_acc = np.sum(test.label == test.pred) / len(test)
test_acc

0.9963420273292325

NameError: name 'model' is not defined