In [1]:
import json
import os
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import random

### coco: 894 // flickr: 184 // open_image: 616

In [2]:
dir_path = "../Data/disaster/train"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)


disaster = img_names
print(len(disaster))

10057


In [3]:
## open_image 8000장
dir_path = "../../disk/Data/open_image/train_0/"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)
open_image_non = img_names[:35000]
print(len(open_image_non))

35000


In [4]:
## coco_image 1만장
dir_path = "../Data/train2017"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)
coco_non = img_names[:35000]
print(len(coco_non))

35000


In [5]:
print(coco_non[:3])

['../Data/train2017/000000102848.jpg', '../Data/train2017/000000536933.jpg', '../Data/train2017/000000067269.jpg']


In [6]:
non = coco_non + open_image_non
random.shuffle(non)
print(len(non))

70000


##### labeling

##### split train, test

In [7]:
### train: test (4:1)
## 36000 (1/4), 4000 (1/4)
# non_ratio=6400
# dis_ratio=6400
# trn_disater = non[:non_ratio] + disaster[:dis_ratio]
# tst_disater = non[non_ratio:] + disaster[dis_ratio:]
# trn_label = [0]*int(len(non[:non_ratio])) + [1]*int(len(disaster[:dis_ratio]))
# tst_label = [0]*int(len(non[non_ratio:])) + [1]*int(len(disaster[dis_ratio:]))
# print(len(trn_label))
# print(len(tst_label))

In [8]:
trn_disater = non + disaster
trn_label = [0]*int(len(non)) + [1]*int(len(disaster))
print(len(trn_label))

80057


In [9]:
trn_df = pd.DataFrame(trn_disater, columns=['image_id'])
trn_df['dir'] = trn_df['image_id'].apply(lambda x: os.path.dirname(x))
trn_df['image_id'] = trn_df['image_id'].apply(lambda x: os.path.basename(x))
trn_df['label'] = trn_label
train = trn_df
train

image_id  \
0                                       000000104452.jpg   
1                                   0c3e3a3c67c8692b.jpg   
2                                       000000440641.jpg   
3                                   03d7e52db226a17c.jpg   
4                                   0a736f35f26470b5.jpg   
...                                                  ...   
80052                  earthquake_284_HorizontalFlip.jpg   
80053                                 earthquake_262.jpg   
80054                      earthquake_301_rotatation.jpg   
80055                      32f367406aeab9c0_contrast.jpg   
80056  In this image we can see a group of trees and ...   

                                                     dir  label  
0                                      ../Data/train2017      0  
1                     ../../disk/Data/open_image/train_0      0  
2                                      ../Data/train2017      0  
3                     ../../disk/Data/open_image/train_0      0  
4                     ../../disk/Data/open_image/train_0      0  
...                                                  ...    ...  
80052    ../Data/disaster/train/augmented/HorizontalFlip      1  
80053  ../Data/disaster/train/origin_images/crawling/...      1  
80054        ../Data/disaster/train/augmented/rotatation      1  
80055          ../Data/disaster/train/augmented/contrast      1  
80056       ../Data/disaster/train/generated1/open_image      1  

[80057 rows x 3 columns]

In [10]:
project_name = 'disaster_classfication_inception_resnet_v2_7010_a'
user = 'hojunking'
run_name = 'disaster_classfication_inception_resnet_v2_7010_a'

In [11]:
%run classification_baseline.ipynb

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: hojunking. Use `wandb login --relogin` to force relogin


Model: inception_resnet_v2
Training start with fold: 0 epoch: 200 

All training process
Fold: 0
Epoch 0/199


epoch 0 loss: 0.0391: 100%|███████████████████| 501/501 [04:05<00:00,  2.04it/s]


Fold: 0
Epoch 1/199


epoch 1 loss: 0.0430: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]


Fold: 0
Epoch 2/199


epoch 2 loss: 0.0605: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.970395568495205
Fold: 0
Epoch 3/199



epoch 3 loss: 0.0432: 100%|███████████████████| 501/501 [02:03<00:00,  4.07it/s]


Fold: 0
Epoch 4/199


epoch 4 loss: 0.0424: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]


Fold: 0
Epoch 5/199


epoch 5 loss: 0.0471: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9733840086481471
Fold: 0
Epoch 6/199



epoch 6 loss: 0.0376: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]


Fold: 0
Epoch 7/199


epoch 7 loss: 0.0403: 100%|███████████████████| 501/501 [02:03<00:00,  4.07it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9794835114818332
Fold: 0
Epoch 8/199



epoch 8 loss: 0.0379: 100%|███████████████████| 501/501 [02:03<00:00,  4.07it/s]


Fold: 0
Epoch 9/199


epoch 9 loss: 0.0412: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9803047060006375
Fold: 0
Epoch 10/199



epoch 10 loss: 0.0437: 100%|██████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9803047060006375
Fold: 0
Epoch 11/199



epoch 11 loss: 0.0381: 100%|██████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9803047060006375
Fold: 0
Epoch 12/199



epoch 12 loss: 0.0389: 100%|██████████████████| 501/501 [02:03<00:00,  4.07it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9803047060006375
Fold: 0
Epoch 13/199



epoch 13 loss: 0.0485: 100%|██████████████████| 501/501 [02:03<00:00,  4.06it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9803047060006375
stop called
time : 2:05:47
fold: 0, Best Epoch : 8/ 14
fold: 0, Best Train Marco F1 : 0.99787
[[55968    32]
 [   28  8017]]
fold: 0, Best Valid Marco F1 : 0.98030
[[13941    59]
 [   79  1933]]
---------------------------------------------------------
Training start with fold: 1 epoch: 200 

All training process
Fold: 1
Epoch 0/199


epoch 0 loss: 0.0338: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]


Fold: 1
Epoch 1/199


epoch 1 loss: 0.0297: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]


Fold: 1
Epoch 2/199


epoch 2 loss: 0.0370: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9795533281602296
Fold: 1
Epoch 3/199



epoch 3 loss: 0.0429: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9795533281602296
Fold: 1
Epoch 4/199



epoch 4 loss: 0.0440: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9795533281602296
Fold: 1
Epoch 5/199



epoch 5 loss: 0.0453: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9795533281602296
Fold: 1
Epoch 6/199



epoch 6 loss: 0.0404: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9795533281602296
stop called
time : 0:58:18
fold: 1, Best Epoch : 1/ 7
fold: 1, Best Train Marco F1 : 0.99192
[[55906    94]
 [  133  7912]]
fold: 1, Best Valid Marco F1 : 0.97955
[[13926    74]
 [   70  1942]]
---------------------------------------------------------
Training start with fold: 2 epoch: 200 

All training process
Fold: 2
Epoch 0/199


epoch 0 loss: 0.0325: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]


Fold: 2
Epoch 1/199


epoch 1 loss: 0.0303: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]


Fold: 2
Epoch 2/199


epoch 2 loss: 0.0438: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9790006981064169
Fold: 2
Epoch 3/199



epoch 3 loss: 0.0393: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9790006981064169
Fold: 2
Epoch 4/199



epoch 4 loss: 0.0437: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9790006981064169
Fold: 2
Epoch 5/199



epoch 5 loss: 0.0449: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9790006981064169
Fold: 2
Epoch 6/199



epoch 6 loss: 0.0351: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9790006981064169
stop called
time : 0:59:09
fold: 2, Best Epoch : 1/ 7
fold: 2, Best Train Marco F1 : 0.99211
[[55896   104]
 [  118  7928]]
fold: 2, Best Valid Marco F1 : 0.97900
[[13954    46]
 [  100  1911]]
---------------------------------------------------------
Training start with fold: 3 epoch: 200 

All training process
Fold: 3
Epoch 0/199


epoch 0 loss: 0.0376: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]


Fold: 3
Epoch 1/199


epoch 1 loss: 0.0571: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.968951031719669
Fold: 3
Epoch 2/199



epoch 2 loss: 0.0401: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]


Fold: 3
Epoch 3/199


epoch 3 loss: 0.0439: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]


Fold: 3
Epoch 4/199


epoch 4 loss: 0.0467: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9729689849383505
Fold: 3
Epoch 5/199



epoch 5 loss: 0.0369: 100%|███████████████████| 501/501 [02:04<00:00,  4.04it/s]


Fold: 3
Epoch 6/199


epoch 6 loss: 0.0428: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9769870664179912
Fold: 3
Epoch 7/199



epoch 7 loss: 0.0461: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9769870664179912
Fold: 3
Epoch 8/199



epoch 8 loss: 0.0433: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9769870664179912
Fold: 3
Epoch 9/199



epoch 9 loss: 0.0591: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9769870664179912
Fold: 3
Epoch 10/199



epoch 10 loss: 0.0417: 100%|██████████████████| 501/501 [02:03<00:00,  4.05it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9769870664179912
stop called
time : 1:33:15
fold: 3, Best Epoch : 5/ 11
fold: 3, Best Train Marco F1 : 0.99730
[[55962    38]
 [   38  8008]]
fold: 3, Best Valid Marco F1 : 0.97699
[[13947    53]
 [  107  1904]]
---------------------------------------------------------
Training start with fold: 4 epoch: 200 

All training process
Fold: 4
Epoch 0/199


epoch 0 loss: 0.0332: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]


Fold: 4
Epoch 1/199


epoch 1 loss: 0.0455: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9729217732247109
Fold: 4
Epoch 2/199



epoch 2 loss: 0.0508: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9729217732247109
Fold: 4
Epoch 3/199



epoch 3 loss: 0.0424: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9729217732247109
Fold: 4
Epoch 4/199



epoch 4 loss: 0.0382: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]


Fold: 4
Epoch 5/199


epoch 5 loss: 0.0398: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]


Fold: 4
Epoch 6/199


epoch 6 loss: 0.0477: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9737905933351478
Fold: 4
Epoch 7/199



epoch 7 loss: 0.0466: 100%|███████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9737905933351478
Fold: 4
Epoch 8/199



epoch 8 loss: 0.0369: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]


Fold: 4
Epoch 9/199


epoch 9 loss: 0.0355: 100%|███████████████████| 501/501 [02:03<00:00,  4.05it/s]


Fold: 4
Epoch 10/199


epoch 10 loss: 0.0402: 100%|██████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9796562069910097
Fold: 4
Epoch 11/199



epoch 11 loss: 0.0345: 100%|██████████████████| 501/501 [02:03<00:00,  4.06it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9796562069910097
Fold: 4
Epoch 12/199



epoch 12 loss: 0.0338: 100%|██████████████████| 501/501 [02:03<00:00,  4.06it/s]


Fold: 4
Epoch 13/199


epoch 13 loss: 0.0470: 100%|██████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 1 out of 5
Best F1 score from now: 0.9813075769005415
Fold: 4
Epoch 14/199



epoch 14 loss: 0.0297: 100%|██████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 2 out of 5
Best F1 score from now: 0.9813075769005415
Fold: 4
Epoch 15/199



epoch 15 loss: 0.0413: 100%|██████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 3 out of 5
Best F1 score from now: 0.9813075769005415
Fold: 4
Epoch 16/199



epoch 16 loss: 0.0437: 100%|██████████████████| 501/501 [02:03<00:00,  4.05it/s]

EarlyStopping counter: 4 out of 5
Best F1 score from now: 0.9813075769005415
Fold: 4
Epoch 17/199



epoch 17 loss: 0.0486: 100%|██████████████████| 501/501 [02:03<00:00,  4.05it/s]


EarlyStopping counter: 5 out of 5
Best F1 score from now: 0.9813075769005415
stop called
time : 2:32:35
fold: 4, Best Epoch : 12/ 18
fold: 4, Best Train Marco F1 : 0.99819
[[55972    28]
 [   23  8023]]
fold: 4, Best Valid Marco F1 : 0.98131
[[13943    57]
 [   74  1937]]
---------------------------------------------------------
best_fold : 0.9813075769005415
 Top fold : 4


In [12]:
dir_path = "../Data/disaster/test"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)

disaster_test = img_names
print(len(disaster_test))

400


In [13]:
## open_image 1만장
dir_path = "../../disk/Data/open_image/train_1/"

img_names = []
for folder, subfolders, filenames in os.walk(dir_path):
    for img in filenames:
        img_names.append(folder+'/'+img)
random.shuffle(img_names)
open_image_non_test = img_names[:20000]
print(len(open_image_non_test))

20000


In [14]:
tst_disater = open_image_non_test + disaster_test
tst_label = [0]*int(len(open_image_non_test)) + [1]*int(len(disaster_test))
print(len(tst_label))

20400


In [15]:
tst_df = pd.DataFrame(tst_disater, columns=['image_id'])
tst_df['dir'] = tst_df['image_id'].apply(lambda x: os.path.dirname(x))
tst_df['image_id'] = tst_df['image_id'].apply(lambda x: os.path.basename(x))
tst_df['label'] = tst_label
test = tst_df
test

image_id  \
0                   136458d0da88828b.jpg   
1                   10745c353b5ac23c.jpg   
2                   1acdf3a5be90b86a.jpg   
3                   1e96463d79b68919.jpg   
4                   116ea9f20bc62c1d.jpg   
...                                  ...   
20395  blizzard_disasterblizzard_123.jpg   
20396                    tempest_043.jpg   
20397               32ce6407b55b36a5.jpg   
20398                   000000328569.jpg   
20399               thunderstorm_346.jpg   

                                                     dir  label  
0                     ../../disk/Data/open_image/train_1      0  
1                     ../../disk/Data/open_image/train_1      0  
2                     ../../disk/Data/open_image/train_1      0  
3                     ../../disk/Data/open_image/train_1      0  
4                     ../../disk/Data/open_image/train_1      0  
...                                                  ...    ...  
20395  ../Data/disaster/test/origin_images/crawling/b...      1  
20396  ../Data/disaster/test/origin_images/crawling/t...      1  
20397  ../Data/disaster/test/origin_images/open_image...      1  
20398  ../Data/disaster/test/origin_images/COCO_disaster      1  
20399  ../Data/disaster/test/origin_images/crawling/t...      1  

[20400 rows x 3 columns]

In [12]:
dist.destroy_process_group()

In [16]:
model_name = 'inception_resnet_v2'
model_dir = model_name + '/inception_resnet_v2_4'
%run eval_test.ipynb

100%|█████████████████████████████████████████| 160/160 [06:08<00:00,  2.30s/it]


In [17]:
print(f'accuracy: {test_acc:.4f}')
print(f'f1_score: {epoch_f1:.4f}')
print(f'confusion_matrix \n-------------------------\n {test_matrix}')

accuracy: 0.9900
f1_score: 0.8729
confusion_matrix 
-------------------------
 [[19891   109]
 [   94   306]]


In [11]:
non_matched_idx = test['label'] != test['pred']
non_matched = test[non_matched_idx].reset_index(inplace = False, drop=True)
non_matched

image_id  \
0                 13d191db596a5e4a.jpg   
1                 1cfd32a632fa0771.jpg   
2                 1a7a43cb6ae3ed7b.jpg   
3                 1410f35aeb2ae8af.jpg   
4                 13628048cf4a80cd.jpg   
..                                 ...   
558  blizzard_disasterblizzard_305.jpg   
559                    tempest_041.jpg   
560                   000000073187.jpg   
561                   000000234697.jpg   
562                   000000213826.jpg   

                                                   dir  label  pred  \
0                   ../../disk/Data/open_image/train_1      0     1   
1                   ../../disk/Data/open_image/train_1      0     1   
2                   ../../disk/Data/open_image/train_1      0     1   
3                   ../../disk/Data/open_image/train_1      0     1   
4                   ../../disk/Data/open_image/train_1      0     1   
..                                                 ...    ...   ...   
558  ../Data/disaster/test/origin_images/crawling/b...      1     0   
559  ../Data/disaster/test/origin_images/crawling/t...      1     0   
560  ../Data/disaster/test/origin_images/COCO_disaster      1     0   
561  ../Data/disaster/test/origin_images/COCO_disaster      1     0   
562  ../Data/disaster/test/origin_images/COCO_disaster      1     0   

     confidence score  
0            0.918041  
1            0.700170  
2            0.665575  
3            0.993265  
4            0.930421  
..                ...  
558          0.924526  
559          0.999252  
560          0.999304  
561          0.999646  
562          0.992844  

[563 rows x 5 columns]

In [ ]:
## show img status

back = 0
plt.figure(figsize=(16,600))
for i in range(len(non_matched[back:])):
    plt.subplot(150,4,i+1)
    #if i % 4 == 0:
        #plt.title(f"{(i+1+back)/4}")
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    path = non_matched['dir'][i+back] + '/' + non_matched['image_id'][i+back]
    im_bgr = cv2.imread(path)
    im_rgb = im_bgr[:, :, ::-1]
    plt.imshow(im_rgb, cmap=plt.cm.binary)
    
plt.show()

In [24]:
test.to_csv('test_result/nsb2_oi_tst.csv', index=False)

In [8]:
test_acc = np.sum(test.label == test.pred) / len(test)
test_acc

0.9963420273292325

NameError: name 'model' is not defined